export const RECOMMEND_IDEAS_FETCH_REQUEST = 'RECOMMEND_IDEAS_FETCH_REQUEST';
export const RECOMMEND_IDEAS_FETCH_SUCCESS = 'RECOMMEND_IDEAS_FETCH_SUCCESS';
export const RECOMMEND_IDEAS_FETCH_ERROR = 'RECOMMEND_IDEAS_FETCH_ERROR';

export const RECOMMEND_PROJECTS_FETCH_REQUEST = 'RECOMMEND_PROJECTS_FETCH_REQUEST';
export const RECOMMEND_PROJECTS_FETCH_SUCCESS = 'RECOMMEND_PROJECTS_FETCH_SUCCESS';
export const RECOMMEND_PROJECTS_FETCH_ERROR = 'RECOMMEND_PROJECTS_FETCH_ERROR';

export const IDEAS_FETCH_REQUEST = 'IDEAS_FETCH_REQUEST';
export const IDEAS_FETCH_SUCCESS = 'IDEAS_FETCH_SUCCESS';
export const IDEAS_FETCH_ERROR = 'IDEAS_FETCH_ERROR';

export const PROJECTS_FETCH_REQUEST = 'PROJECTS_FETCH_REQUEST';
export const PROJECTS_FETCH_SUCCESS = 'PROJECTS_FETCH_SUCCESS';
export const PROJECTS_FETCH_ERROR = 'PROJECTS_FETCH_ERROR';

export const DETAIL_FETCH_REQUEST = 'DETAIL_FETCH_REQUEST';
export const DETAIL_FETCH_SUCCESS = 'DETAIL_FETCH_SUCCESS';
export const DETAIL_FETCH_ERROR = 'DETAIL_FETCH_ERROR';

export const CLASSIFIES_FETCH_REQUEST = 'CLASSIFIES_FETCH_REQUEST';
export const CLASSIFIES_FETCH_SUCCESS = 'CLASSIFIES_FETCH_SUCCESS';
export const CLASSIFIES_FETCH_ERROR = 'CLASSIFIES_FETCH_ERROR';
