export const HOME_FETCH_REQUEST = 'HOME_FETCH_REQUEST';
export const HOME_FETCH_SUCCESS = 'HOME_FETCH_SUCCESS';
export const HOME_FETCH_ERROR = 'HOME_FETCH_ERROR';

export const IDEAS_FETCH_REQUEST = 'IDEAS_FETCH_REQUEST';
export const IDEAS_FETCH_SUCCESS = 'IDEAS_FETCH_SUCCESS';
export const IDEAS_FETCH_ERROR = 'IDEAS_FETCH_ERROR';

export const DETAIL_FETCH_REQUEST = 'DETAIL_FETCH_REQUEST';
export const DETAIL_FETCH_SUCCESS = 'DETAIL_FETCH_SUCCESS';
export const DETAIL_FETCH_ERROR = 'DETAIL_FETCH_ERROR';
