module.exports = {
    production: {
        devtool: false,
        NODE_ENV: 'production',
        HOST: 'www.website.com',
        API: 'www.website.com/api',
        jsSourceMap: false,
        cssSourceMap: false,
        eslint: false,
        filePath: '',
        staticPath: '',
        cssPath: '',
        imgPath: '',
        filenameHash: true,
    },
    test: {
        devtool: false,
        NODE_ENV: 'test',
        HOST: 'test.website.com',
        API: 'test.website.com/api',
        jsSourceMap: false,
        cssSourceMap: false,
        eslint: false,
        filePath: '',
        staticPath: '',
        cssPath: '',
        imgPath: '',
        filenameHash: false,
    },
    development: {
        port: 9000,
        devtool: 'source-map',
        NODE_ENV: 'development',
        HOST: 'dev.website.com',
        API: 'dev.website.com/api',
        jsSourceMap: false,
        cssSourceMap: false,
        eslint: false,
        staticPath: '/',
        filePath: '',
        cssPath: '',
        imgPath: '',
        filenameHash: false,
    }
};
